[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python /app/bot.py"

[variables]
BOT_TOKEN = "8342380801:AAFYCtKncWloIoYyQ3EAnaocnOzWohPAHXc"
ADMIN_IDS = "7634753556"
